version: "3.9"

services:
  myapp:
    container_name: weaver_dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_USERNAME: ${SSH_USERNAME}
        SSH_PASSWORD: ${SSH_PASSWORD}
        DOCKER_WEB_PORT: ${DOCKER_WEB_PORT}
        DOCKER_SSH_PORT: ${DOCKER_SSH_PORT}
    image: weaver_dev:tag
    env_file:
      - ./.env
    ports:
      - "${WEB_PORT}:${DOCKER_WEB_PORT}"
      - "${SSH_PORT}:${DOCKER_SSH_PORT}"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      WEB_PORT: ${WEB_PORT}
      SQLALCHEMY_DATABASE_URI: "sqlite:///myapp.db"
      SQLALCHEMY_TRACK_MODIFICATIONS: "false"
    volumes:
      - ..:/app
      - /etc/timezone:/etc/timezone:ro
