version: '3.8'
services:
  weaver_prod:
    build: .
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env