version: '3.8'
services:
  weaver_prod:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

    db:
    image: postgres
    environment:
      POSTGRES_DB: weaverdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - weaver_prod_postgres_data:/var/lib/postgresql/data

volumes:
  weaver_prod_postgres_data: