"""add_veda_orders_table

Revision ID: a7efb08f089a
Revises: 001_initial
Create Date: 2026-02-02 18:18:19.591362+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7efb08f089a'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veda_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_order_id', sa.String(length=36), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('time_in_force', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('filled_avg_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_veda_orders_run_status', 'veda_orders', ['run_id', 'status'], unique=False)
    op.create_index('idx_veda_orders_symbol_status', 'veda_orders', ['symbol', 'status'], unique=False)
    op.create_index(op.f('ix_veda_orders_client_order_id'), 'veda_orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_veda_orders_run_id'), 'veda_orders', ['run_id'], unique=False)
    op.create_index(op.f('ix_veda_orders_status'), 'veda_orders', ['status'], unique=False)
    op.create_index(op.f('ix_veda_orders_symbol'), 'veda_orders', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veda_orders_symbol'), table_name='veda_orders')
    op.drop_index(op.f('ix_veda_orders_status'), table_name='veda_orders')
    op.drop_index(op.f('ix_veda_orders_run_id'), table_name='veda_orders')
    op.drop_index(op.f('ix_veda_orders_client_order_id'), table_name='veda_orders')
    op.drop_index('idx_veda_orders_symbol_status', table_name='veda_orders')
    op.drop_index('idx_veda_orders_run_status', table_name='veda_orders')
    op.drop_table('veda_orders')
    # ### end Alembic commands ###
